version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.9
    ports: 
        - 50000:50000
        - 80:80
        - 443:443
    volumes: 
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/nginx/ssl
        - /etc/localtime:/etc/localtime
    links:
        - backend:backend
        - frontend:frontend
  mongodb:
    container_name: mongodb
    image: mongo:4.4.5
    volumes: 
        - ./data:/data/db
        - /etc/localtime:/etc/localtime
    ports:
        - 127.0.0.1:27017:27017
  backend:
    container_name: backend
    image: ${backendImage}
    environment: 
        - mongoURI=mongodb:27017
    depends_on:
        - mongodb
    volumes:
        - /etc/localtime:/etc/localtime
    links:
        - mongodb:mongodb
    dns:
        - 8.8.8.8
        - 4.2.2.1
        - 4.2.2.2
        - 1.1.1.1
        - 114.114.114.114
  frontend:
    container_name: frontend
    image: ${frontendImage}
    environment:
        - backendURI=http://backend:50000
    volumes:
        - /etc/localtime:/etc/localtime
    links:
        - backend:backend
